name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: prepor/action-aws-iam-authenticator@master
      - run: aws-iam-authenticator version
